### ISSUE TITLE
Violation of MIT license?

### ISSUE THREAD

**Issue by hfossli-agens** [chieffancypants/fast-mutex#6]
I noticed this code
https://github.com/chieffancypants/fast-mutex/blob/master/dist/fast-mutex.js#L580-L703

is identical with this code
https://github.com/thevtm/ms/blob/3d1e2b710314595596d5212639df419cfd860cb4/index.js

Did you copy without complying with the license from that thevtm/ms? Or is there another source? In any case this is quick to remedy as you only have to add the license below your own license. 

Let me know if you have any questions.

Just thought you should know as we in the open source community benefit from treating other peoples licenses with outmost respect :) Cheers!

**Comment by VanTanev** [comment]
Fast-mutex is under ISC license, which as per github is:

> A permissive license lets people do anything with your code with proper attribution and without warranty. The ISC license is functionally equivalent to the BSD 2-Clause and MIT licenses, removing some language that is no longer necessary.

What's the purpose of this issue?

**Comment by hfossli-agens** [comment]
The author of this library have copied code from another repository without respecting the license. Their [MIT license](https://github.com/thevtm/ms/blob/master/license.md) is pretty clear here 

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

I don't see the MIT license. I'm opening a pull request.

**Comment by chieffancypants** [comment]
Hi there.  I'm getting back into some open source work and finally getting around to this.

The `dist` folder is the compiled / concatenated output of this library, and all other libraries it depends upon.  I have no idea how you recognized that code, but you are indeed correct, it is from the `ms` package, which is depended upon by the `debug` package.

In other words, this is not part of my source code which is why it's not listed in the license.
